<?php

namespace AppBundle\Repository;

/**
 * CategorieDeServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieDeServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
