<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Prestataire;
use Doctrine\ORM\EntityRepository;

/**
 * PrestataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestataireRepository extends EntityRepository
{
    public function findPrestataires($slug)
    {
        if($slug != null){
            $data = $this->findOneBy(array('slug'=> $slug));
            $gc = $this->getCote($data);
            $cote = $gc[0]['cote'];
            $data->cote = $cote;
        }else {
            $data = $this->findAll();
            foreach ($data as $prest)
            {
                $gc = $this->getCote($prest);
                $cote = $gc[0]['cote'];
                $prest->cote = $cote;
            }
        }
        return $data;
    }

    public function getCote(Prestataire $prestataire)
    {
        $query = $this->getEntityManager()->createQuery("SELECT (AVG(c.cote)/5) cote FROM AppBundle:Commentaire c WHERE c.cibleCommentaire = ?1");
        $query->setParameter(1,$prestataire);
        $result = $query->getResult();

        return $result;
    }
}
